main: hpms.discordchat.chat.DiscordChat
name: DiscordChat
author: GitHub/hpmss
version: 1.0
description: Chatting in channels.
commands:
      discordchat:
         aliases: dc
         description: Main command.
         permission: discordchat.commands
      flush:
         aliases: f
         description: Flush the chat.
         permission: discordchat.flush
         
permissions:
      discordchat.overridechannel:
         default: op
      discordchat.multiplechannel:
         default: op
      discordchat.flush:
         default: op
      discordchat.commands:
         default: op
      discordchat.bypassjoin:
         default: op