main: hpms.discordchat.chat.DiscordChat
name: DiscordChat
author: GitHub/hpmss
version: 1.0
description: Chatting in channels.
commands:
      discordchat:
         aliases: dc
         description: Main command.
         permission: discordchat.commands
      flush:
         aliases: f
         description: Flush the chat.
         permission: discordchat.flush
permissions:
      discordchat.overridechannel:
         default: op
      discordchat.multiplechannel:
         default: op
      dc.default:
         default: op
      dc.godsetrole:
         default: op
      dc.godsetroleprefix:
         default: op
      dc.godsetchannelprefix:
         default: op
      dc.godaddrole:
         default: op
      dc.godremoverole:
         default: op
      discordchat.flush:
         default: op
      discordchat.commands:
         default: true
      discordchat.bypassjoin:
         default: op
      discordchat.sad:
         default: true
      discordchat.basiccommand:
         default: true
       